/* eslint-disable prettier/prettier */
export const PROCESSES = [
  {
    id: 101,
    name: "Catálogo 1",
    processes: [
      {
        id: 1,
        PID: 1234,
        name: "proceso1",
        user: "usuario1",
        description: "qwertyuiop",
        priority: "alta",
      },
      {
        id: 2,
        PID: 5678,
        name: "proceso2",
        user: "usuario2",
        description: "qwe",
        priority: "media",
      },
      {
        id: 3,
        PID: 91011,
        name: "proceso3",
        user: "usuario3",
        description: "qwertyui",
        priority: "alta",
      },
      {
        id: 4,
        PID: 121314,
        name: "proceso4",
        user: "usuario1",
        description: "qwert",
        priority: "baja",
      },
      {
        id: 5,
        PID: 151617,
        name: "proceso5",
        user: "usuario2",
        description: "qwertyuiopas",
        priority: "media",
      },
    ],
  },
  {
    id: 102,
    name: "Catálogo 2",
    processes: [
      {
        id: 6,
        PID: 181920,
        name: "proceso6",
        user: "usuario3",
        description: "Descripción del proceso 6",
        priority: "alta",
      },
      {
        id: 7,
        PID: 212223,
        name: "proceso7",
        user: "usuario1",
        description: "Descripción del proceso 7",
        priority: "media",
      },
      {
        id: 8,
        PID: 242526,
        name: "proceso8",
        user: "usuario2",
        description: "Descripción del proceso 8",
        priority: "alta",
      },
      {
        id: 9,
        PID: 272829,
        name: "proceso9",
        user: "usuario3",
        description: "Descripción del proceso 9",
        priority: "baja",
      },
      {
        id: 10,
        PID: 303132,
        name: "proceso10",
        user: "usuario1",
        description: "Descripción del proceso 10",
        priority: "media",
      },
    ],
  },
  {
    id: 103,
    name: "Catálogo 3",
    processes: [
      {
        id: 11,
        PID: 333435,
        name: "proceso11",
        user: "usuario2",
        description: "Descripción del proceso 11",
        priority: "alta",
      },
      {
        id: 12,
        PID: 363738,
        name: "proceso12",
        user: "usuario3",
        description: "Descripción del proceso 12",
        priority: "media",
      },
      {
        id: 13,
        PID: 394041,
        name: "proceso13",
        user: "usuario1",
        description: "Descripción del proceso 13",
        priority: "alta",
      },
      {
        id: 14,
        PID: 424344,
        name: "proceso14",
        user: "usuario2",
        description: "Descripción del proceso 14",
        priority: "baja",
      },
      {
        id: 15,
        PID: 454647,
        name: "proceso15",
        user: "usuario3",
        description: "Descripción del proceso 15",
        priority: "media",
      },
    ],
  },
  {
    id: 104,
    name: "Catálogo 4",
    processes: [
      {
        id: 16,
        PID: 484950,
        name: "proceso16",
        user: "usuario1",
        description: "Descripción del proceso 16",
        priority: "alta",
      },
      {
        id: 17,
        PID: 515253,
        name: "proceso17",
        user: "usuario2",
        description: "Descripción del proceso 17",
        priority: "media",
      },
      {
        id: 18,
        PID: 545556,
        name: "proceso18",
        user: "usuario3",
        description: "Descripción del proceso 18",
        priority: "alta",
      },
      {
        id: 19,
        PID: 575859,
        name: "proceso19",
        user: "usuario1",
        description: "Descripción del proceso 19",
        priority: "baja",
      },
      {
        id: 20,
        PID: 606162,
        name: "proceso20",
        user: "usuario2",
        description: "Descripción del proceso 20",
        priority: "media",
      },
    ],
  },
  {
    id: 105,
    name: "Catálogo 5",
    processes: [
      {
        id: 21,
        PID: 636465,
        name: "proceso21",
        user: "usuario3",
        description: "Descripción del proceso 21",
        priority: "alta",
      },
      {
        id: 22,
        PID: 666768,
        name: "proceso22",
        user: "usuario1",
        description: "Descripción del proceso 22",
        priority: "media",
      },
      {
        id: 23,
        PID: 697071,
        name: "proceso23",
        user: "usuario2",
        description: "Descripción del proceso 23",
        priority: "alta",
      },
      {
        id: 24,
        PID: 727374,
        name: "proceso24",
        user: "usuario3",
        description: "Descripción del proceso 24",
        priority: "baja",
      },
      {
        id: 25,
        PID: 757677,
        name: "proceso25",
        user: "usuario1",
        description: "Descripción del proceso 25",
        priority: "media",
      },
    ],
  },
];
